version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - "9432:5432"
  redis:
    image: redis:latest
  web:
    build: .
    volumes:
      - .:/code
    command: bash -c "
      python3 manage.py migrate
      && python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
